name: in-orbit-server

services:
  db:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker 
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inorbit
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - inorbit-network
  
  backend:
    build:
      context: ./server
    ports:
      - "3333:3333"
    depends_on:
      - db
    networks:
      - inorbit-network

  frontend:
    build:
      context: ./web
    ports:
      - "5173:5173"
    networks:
      - inorbit-network

volumes:
  pgdata:

networks:
  inorbit-network:
